stages:
  data_ingestion:
    cmd: python src/housing/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/housing/pipeline/stage_01_data_ingestion.py
      - src/housing/components/data_ingestion.py
      - src/housing/config/configuration.py
      - src/housing/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/

## update as per your requirements