stages:
  data_ingestion:
    cmd: python src/housing/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/housing/pipeline/stage_01_data_ingestion.py
      - src/housing/components/data_ingestion.py
      - src/housing/config/configuration.py
      - src/housing/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/

  data_process:
    cmd: python src/housing/pipeline/stage_02_data_process.py
    deps:
      - artifacts/data_ingestion/
      - src/housing/pipeline/stage_02_data_process.py
      - src/housing/components/data_process.py
      - src/housing/config/configuration.py
      - src/housing/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_process/

  model_train:
    cmd: python src/housing/pipeline/stage_03_model_train.py
    deps:
      - artifacts/data_process/
      - src/housing/pipeline/stage_03_model_train.py
      - src/housing/components/model_train.py
      - src/housing/config/configuration.py
      - src/housing/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/model_train/

  model_evaluation:
    cmd: python src/housing/pipeline/stage_04_model_evaluation.py
    deps:
      - artifacts/model_train/
      - src/housing/pipeline/stage_04_model_evaluation.py
      - src/housing/components/model_evaluation.py
      - src/housing/config/configuration.py
      - src/housing/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/model_evaluation/