artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_URL: https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz
  tar_filepath: artifacts/data_ingestion/housing.tgz
  untar_filepath: artifacts/data_ingestion/
  prepared_datapath: artifacts/data_ingestion/raw_data.csv