artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_URL: https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz
  tar_filepath: artifacts/data_ingestion/housing.tgz
  untar_filepath: artifacts/data_ingestion/
  prepared_datapath: artifacts/data_ingestion/raw_data.csv

data_process:
  root_dir: artifacts/data_process
  data_filepath: artifacts/data_ingestion/raw_data.csv
  scaled_pickle_file: artifacts/data_process/scaler.pkl
  training_data_filepath: artifacts/data_process/train_data/
  test_data_filepath: artifacts/data_process/test_data/
  train_X_datapath: artifacts/data_process/train_data/train_X.csv
  train_y_datapath: artifacts/data_process/train_data/train_y.csv
  test_X_datapath: artifacts/data_process/test_data/test_X.csv
  test_y_datapath: artifacts/data_process/test_data/test_y.csv

model_train:
  root_dir: artifacts/model_train
  train_X_datapath: artifacts/data_process/train_data/train_X.csv
  train_y_datapath: artifacts/data_process/train_data/train_y.csv
  model_1_pickle_file: artifacts/model_train/reg_model_1.pkl
  